## Pre-Processing

This is the pre-processing notebook file for our Final Project.

The end goal of this pre-processing will be to clean out the data so that we only have the countries that we want to classify (countries of the G20) and only have economic indicators from the World Bank.

In [1]:
import pandas as pd
import numpy as np

dataset = pd.read_csv("WDIData.csv")
dataset

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.936004,17.337896,17.687093,18.140971,18.491344,18.825520,19.272212,19.628009,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.499471,6.680066,6.859110,7.016238,7.180364,7.322294,7.517191,7.651598,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,37.855399,38.046781,38.326255,38.468426,38.670044,38.722783,38.927016,39.042839,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794160,32.001027,33.871910,38.880173,40.261358,43.061877,44.270860,45.803485,NaN,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.663502,17.633986,16.464681,24.531436,25.345111,27.449908,29.641760,30.404935,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383567,Zimbabwe,ZWE,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,14.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383568,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.700000,NaN,NaN,NaN,5.418352,NaN,NaN,NaN
383569,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.500000,32.400000,NaN,NaN,NaN,33.658057,NaN,NaN,NaN
383570,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,59.100000,59.400000,59.500000,59.700000,59.900000,60.100000,60.300000,60.500000,60.7,NaN
383571,Zimbabwe,ZWE,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,20000.000000,19000.000000,17000.000000,15000.000000,13000.000000,10000.000000,8600.000000,7700.000000,6800.0,NaN

Now that the data is loaded, I'm going to first pull out all non-G20 countries.

The countries that will remain in the dataset that are in the G20 (including members and countries represented by the European Union at G20, so more like G41) are:

<ul>
    <li>Argentina</li>
    <li>Austria</li>
    <li>Australia</li>
    <li>Belgium</li>
    <li>Brazil</li>
    <li>Bulgaria</li>
    <li>Canada</li>
    <li>China</li>
    <li>Croatia</li>
    <li>Cyprus</li>
    <li>Czechia</li>
    <li>Denmark</li>
    <li>Estonia</li>
    <li>Finland</li>
    <li>France</li>
    <li>Germany</li>
    <li>Greece</li>
    <li>Hungary</li>
    <li>India</li>
    <li>Indonesia</li>
    <li>Ireland</li>
    <li>Italy</li>
    <li>Japan</li>
    <li>Latvia</li>
    <li>Lithuania</li>
    <li>Malta</li>
    <li>Mexico</li>
    <li>Netherlands</li>
    <li>Poland</li>
    <li>Portugal</li>
    <li>Slovakia</li>
    <li>Slovenia</li>
    <li>South Korea</li>
    <li>Spain</li>
    <li>Sweden</li>
    <li>Romania</li>
    <li>Russia</li>
    <li>Saudi Arabia</li>
    <li>South Africa</li>
    <li>Turkey</li>
    <li>United Kingdom</li>
    <li>United States</li>
</ul>

In [2]:
countries = ['Argentina', 'Austria', 'Australia', 'Belgium', 'Brazil', 'Bulgaria', 'Canada', 'China', 'Croatia',
            'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'India',
            'Indonesia', 'Ireland', 'Italy', 'Japan', 'Latvia', 'Lithuania', 'Malta', 'Mexico', 'Netherlands',
            'Poland', 'Portugal', 'Slovak Republic', 'Slovenia', 'South Korea', 'Spain', 'Sweden', 'Romania', 
             'Russian Federation', 'Saudi Arabia', 'South Africa', 'Turkiye', 'United Kingdom', 'United States']

dataset = dataset[dataset['Country Name'].isin(countries)]

In [3]:
dataset

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
80752,Argentina,ARG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.600000,99.7,99.700000,99.800000,99.8,99.800000,99.9,99.9,NaN,NaN
80753,Argentina,ARG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,94.300000,95.0,95.500000,96.000000,96.3,96.600000,97.0,97.2,NaN,NaN
80754,Argentina,ARG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.900000,99.9,99.900000,99.900000,99.9,99.900000,99.9,99.9,NaN,NaN
80755,Argentina,ARG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.342674,100.0,99.625389,99.849579,100.0,99.989578,100.0,100.0,NaN,NaN
80756,Argentina,ARG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,94.687187,100.0,97.091499,98.836769,100.0,99.871811,100.0,100.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369147,United States,USA,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369148,United States,USA,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369149,United States,USA,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369150,United States,USA,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.000000,22.8,22.700000,22.500000,22.4,22.300000,22.3,22.2,22.1,NaN
369151,United States,USA,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,8000.000000,7600.0,7300.000000,6800.000000,6500.0,6400.000000,6100.0,NaN,NaN,NaN

Next, I'm going to remove the rows that we don't want related to indicators. This essentially means I'm going to be only including the economic indicators that we decide we are going to use as a group to classify countries into their covid responses. 

The economic indicators that we are going to be using for classification come from an article from the World Bank (which is where the dataset is from) and are "Featured Indicators" when looking at the economy of countries, so it's not every single indicator of a country's economy.

The indicators that will be included are: 

<ul>
    <li>GDP (current US&#36;)</li>
    <li>GDP growth (annual %)</li>
    <li>Agriculture, value added (annual % growth)</li>
    <li>Industry, value added (annual % growth)</li>
    <li>Manufacturing, value added (annual % growth)</li>
    <li>Services, value added (annual % growth)</li>
    <li>Final consumption expenditure (annual % growth)</li>
    <li>Gross capital formation (annual % growth)</li>
    <li>Exports of goods and services (annual % growth)</li>
    <li>Imports of goods and services (annual % growth)</li>
    <li>Agriculture, value added (% of GDP)</li>
    <li>Industry, value added (% of GDP)</li>
    <li>Services, value added (% of GDP)</li>
    <li>Final consumption expenditure (% of GDP)</li>
    <li>Gross capital formation (% of GDP)</li>
    <li>Exports of goods and services (% of GDP)</li>
    <li>Imports of goods and services (% of GDP)</li>
</ul>

Luckily the article provides the code of the indicator, so I can just filter by that then remove that column later.

In [4]:
codes = ['NY.GDP.MKTP.CD', 'NY.GDP.MKTP.KD.ZG', 'NV.AGR.TOTL.KD.ZG', 'NV.IND.TOTL.KD.ZG', 'NV.IND.MANF.KD.ZG',
        'NV.SRV.TOTL.KD.ZG', 'NE.CON.TOTL.KD.ZG', 'NE.GDI.TOTL.KD.ZG', 'NE.EXP.GNFS.KD.ZG', 'NE.IMP.GNFS.KD.ZG',
        'NV.AGR.TOTL.ZS', 'NV.IND.TOTL.ZS', 'NV.SRV.TOTL.ZS', 'NE.CON.TOTL.ZS', 'NE.GDI.TOTL.ZS', 'NE.EXP.GNFS.ZS',
        'NE.IMP.GNFS.ZS']

dataset = dataset[dataset['Indicator Code'].isin(codes)]

In [5]:
dataset

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
80822,Argentina,ARG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,12.904163,...,6.052918,6.712704,5.156686,6.264566,5.231622,4.537879,5.111017,5.932404,6.869856,NaN
80823,Argentina,ARG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,11.476620,3.104253,7.541962,-4.716943,3.445065,-14.581522,21.265569,-7.135723,0.295629,NaN
81148,Argentina,ARG,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,7.604049,5.994947,4.691843,7.890454,5.563716,6.225874,...,14.617173,14.405479,10.705652,12.527095,11.320283,14.436686,17.695944,16.591817,18.300899,NaN
81149,Argentina,ARG,Exports of goods and services (annual % growth),NE.EXP.GNFS.KD.ZG,NaN,-10.638592,45.238463,0.000000,-8.196661,8.928500,...,-3.520240,-6.979167,-2.777373,5.317354,2.615391,0.645996,9.102187,-17.326848,8.988938,NaN
81175,Argentina,ARG,Final consumption expenditure (% of GDP),NE.CON.TOTL.ZS,79.036479,70.100693,79.246140,82.013374,75.900751,75.497032,...,82.793803,82.332955,84.004217,83.376470,84.436467,85.275279,81.936276,79.051086,76.351268,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368330,United States,USA,"Industry (including construction), value added...",NV.IND.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,19.241626,19.331515,18.587132,18.042221,18.436601,18.616777,18.295603,18.438755,NaN,NaN
368331,United States,USA,"Industry (including construction), value added...",NV.IND.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.389576,2.275465,2.367074,0.608765,3.231599,2.974208,2.378995,0.757656,NaN,NaN
368438,United States,USA,"Manufacturing, value added (annual % growth)",NV.IND.MANF.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.809850,1.771980,1.015219,-0.296072,3.357970,4.072325,1.738677,-0.038291,NaN,NaN
368952,United States,USA,"Services, value added (% of GDP)",NV.SRV.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.816054,75.827541,76.742396,77.439693,77.031393,76.739738,77.199503,80.136410,NaN,NaN
368953,United States,USA,"Services, value added (annual % growth)",NV.SRV.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.146261,2.272707,2.723506,1.884232,2.096614,2.865018,2.312761,-0.578015,NaN,NaN

Then, I'm going to remove the columns that we don't want. For example, we only care about the years 2020 and 2021 due to that being the target timeframe of our problem - the COVID-19 pandemic. I'm only going to keep Country Name, Indicator Name, 2020, and 2021.

In [6]:
keep = ['Country Name', 'Indicator Name', '2020', '2021']

dataset = dataset[keep]

In [7]:
dataset

,Country Name,Indicator Name,2020,2021
80822,Argentina,"Agriculture, forestry, and fishing, value adde...",5.932404,6.869856
80823,Argentina,"Agriculture, forestry, and fishing, value adde...",-7.135723,0.295629
81148,Argentina,Exports of goods and services (% of GDP),16.591817,18.300899
81149,Argentina,Exports of goods and services (annual % growth),-17.326848,8.988938
81175,Argentina,Final consumption expenditure (% of GDP),79.051086,76.351268
...,...,...,...,...
368330,United States,"Industry (including construction), value added...",18.438755,NaN
368331,United States,"Industry (including construction), value added...",0.757656,NaN
368438,United States,"Manufacturing, value added (annual % growth)",-0.038291,NaN
368952,United States,"Services, value added (% of GDP)",80.136410,NaN
368953,United States,"Services, value added (annual % growth)",-0.578015,NaN

Now, I'll combine indicators into one row so that one country has one row of data. Before that though, I'm going to look and see if there is a significant number of 2021 data missing and if just the 2020 data would be more viable.

In [8]:
dataset.isna().sum()

Country Name       0
Indicator Name     0
2020               9
2021              43
dtype: int64

Based on that, I will simply just include the 2020 data.

In [9]:
dataset = dataset.drop('2021', axis = 1)

In [10]:
dataset

,Country Name,Indicator Name,2020
80822,Argentina,"Agriculture, forestry, and fishing, value adde...",5.932404
80823,Argentina,"Agriculture, forestry, and fishing, value adde...",-7.135723
81148,Argentina,Exports of goods and services (% of GDP),16.591817
81149,Argentina,Exports of goods and services (annual % growth),-17.326848
81175,Argentina,Final consumption expenditure (% of GDP),79.051086
...,...,...,...
368330,United States,"Industry (including construction), value added...",18.438755
368331,United States,"Industry (including construction), value added...",0.757656
368438,United States,"Manufacturing, value added (annual % growth)",-0.038291
368952,United States,"Services, value added (% of GDP)",80.136410
368953,United States,"Services, value added (annual % growth)",-0.578015

Now onto merging rows. The final product should look like: "Country Name, Indicator1, Indicator2, " and so on.

In [11]:
dataset_pivot = dataset.pivot(index = 'Country Name', columns = 'Indicator Name', values = '2020')

In [12]:
dataset_pivot

Indicator Name,"Agriculture, forestry, and fishing, value added (% of GDP)","Agriculture, forestry, and fishing, value added (annual % growth)",Exports of goods and services (% of GDP),Exports of goods and services (annual % growth),Final consumption expenditure (% of GDP),Final consumption expenditure (annual % growth),GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Gross capital formation (annual % growth),Imports of goods and services (% of GDP),Imports of goods and services (annual % growth),"Industry (including construction), value added (% of GDP)","Industry (including construction), value added (annual % growth)","Manufacturing, value added (annual % growth)","Services, value added (% of GDP)","Services, value added (annual % growth)"
Country Name,,,,,,,,,,,,,,,,,
Argentina,5.932404,-7.135723,16.591817,-17.326848,79.051086,-12.051155,3.895910e+11,-9.895269,14.019730,-11.016885,13.556325,-17.865058,23.311218,-9.369053,-7.760650,54.612674,-10.592109
Australia,2.006092,-10.068572,23.983854,-1.741033,73.802872,-0.416539,1.327836e+12,-0.003837,22.268947,NaN,20.055673,-7.666706,25.462096,0.049462,-1.370961,66.280808,0.643603
Austria,1.099909,-3.060587,51.435008,-10.759174,71.324373,-6.273300,4.332585e+11,-6.734514,25.901203,-4.646383,48.563935,-9.376541,25.457853,-5.659447,-6.997076,63.145665,-7.303380
Belgium,0.638362,-6.824667,80.042038,-5.459022,74.395963,-5.796638,5.216769e+11,-5.680734,24.197411,-6.928552,78.635413,-5.944309,19.479300,-3.093288,-3.687455,69.588938,-5.888087
Brazil,5.893246,3.753746,16.795068,-1.842905,83.369693,-5.223752,1.448566e+12,-3.878676,15.930622,-4.026255,16.095384,-9.840618,17.701653,-3.400928,-4.357614,62.795211,-4.344701
Bulgaria,3.505993,-3.301805,55.323289,-12.066986,78.191183,1.533585,6.988935e+10,-4.387150,20.339766,-5.279527,53.854238,-5.393745,21.923347,-8.218678,NaN,61.253206,-3.338591
Canada,NaN,3.328808,29.363448,-8.692684,79.806948,-4.559653,1.645423e+12,-5.233024,22.257070,-9.818021,31.419082,-10.858232,NaN,-6.310691,-9.685379,NaN,-4.967000
China,7.698643,3.132128,18.541060,NaN,55.330442,-0.273954,1.468767e+13,2.239702,43.366674,4.310804,16.048190,NaN,37.842787,2.464846,NaN,54.458561,1.947954
Croatia,3.216507,3.626613,42.024894,-22.725535,82.849174,-2.819567,5.720378e+10,-8.099761,23.908878,-2.813907,48.782821,-12.260688,21.155324,-1.523108,-3.863769,59.349699,-8.371669
Cyprus,1.930842,-1.384491,75.780512,-5.106329,83.355085,-0.942781,2.469210e+10,-4.984293,19.169241,-11.300714,78.304838,-2.547918,12.606087,-6.383702,-5.435013,74.286844,-4.432524
Denmark,1.306329,6.057835,54.881541,-7.006720,70.623184,-1.450882,3.560849e+11,-2.062125,22.925985,4.513192,48.430708,-4.079737,21.167106,-0.726394,-0.268787,64.550165,-3.027664
Estonia,2.166497,-6.062475,71.175819,-4.977873,71.046638,-0.966600,3.065029e+10,-2.951069,30.243912,14.772244,70.693544,0.856448,22.652102,-4.035191,-8.601872,62.692049,-2.064109
Finland,2.449211,4.506066,35.758734,-7.472933,75.341919,-2.708464,2.718370e+11,-2.299256,24.511859,-0.068067,35.520494,-6.643384,24.033278,-1.121114,-2.058841,60.113448,-3.108664
France,1.596840,-0.145683,27.873644,-15.817148,78.208271,-5.902311,2.630318e+12,-7.855256,23.811869,-9.028705,29.893784,-11.865744,16.445029,-11.229973,-10.932564,71.163379,-7.394614
Germany,0.735310,1.687117,43.416895,-9.319061,73.125735,-3.218028,3.846414e+12,-4.569617,21.149022,-6.366620,37.691652,-8.587234,26.531732,-7.352086,-10.023354,63.312547,-3.831393
Greece,4.230805,-4.214551,31.984002,-21.545369,92.616847,-5.495638,1.888352e+11,-9.019129,14.998070,10.560449,39.598919,-7.630608,14.997499,1.998168,7.468888,68.557587,-11.554613
Hungary,3.380822,-8.652733,79.008742,-6.076234,70.604617,-1.080930,1.567431e+11,-4.463221,27.315589,-6.638799,76.928948,-3.956720,24.627557,-7.201349,-6.996332,56.619027,-3.297772
India,18.228928,3.315789,18.708899,-9.238185,72.855488,-4.542697,2.667688e+12,-6.596081,27.896307,-11.387479,19.096455,-13.810104,24.531066,-3.264418,-0.599385,48.436857,-7.820996
Indonesia,13.702466,1.767005,17.271421,-8.139568,68.501977,-2.098435,1.058689e+12,-2.065005,32.354591,-6.897226,15.704174,-16.717418,38.251605,-2.800136,-2.931807,44.395919,-1.451549
Ireland,0.929474,-1.901458,131.112560,9.497584,37.700220,-5.195717,4.258890e+11,5.866976,40.881999,-22.052679,108.838469,-7.443220,37.953622,20.212608,23.046880,54.786282,-3.502460
Italy,2.009909,-4.738327,29.532511,-13.425831,78.634104,-7.938963,1.892574e+12,-9.025669,17.703516,-10.857464,25.870131,-12.110677,21.606753,-10.272397,-11.444301,66.815761,-8.493965
Japan,1.044271,-6.175335,15.558554,-11.801649,74.826695,-3.234071,5.040108e+12,-4.506905,25.414908,-5.074660,15.800157,-7.164526,29.016842,-4.331568,-6.626689,69.465400,-4.610832
Latvia,4.037779,0.796744,60.438155,-2.153328,77.129972,-4.898283,3.364546e+10,-3.769078,21.695383,-0.770587,59.263510,-2.464941,19.375057,-0.742569,-0.862682,63.492229,-4.904215
Lithuania,3.237023,9.438391,73.501436,0.434040,77.244129,-1.733888,5.654696e+10,-0.132431,13.470174,-13.014688,64.215741,-4.380182,24.978363,1.246179,1.125519,61.605659,-1.177114
Malta,0.437713,-14.817589,149.234806,-5.620201,65.375712,-3.248289,1.491704e+10,-8.348798,21.986185,-7.633401,136.596703,-2.228132,13.399901,-0.779476,-2.193171,76.870718,-8.331920
Mexico,3.798496,0.306680,39.603047,-7.292268,75.671800,-8.936602,1.087118e+12,-8.167358,19.161655,-19.419330,37.555725,-13.734970,29.620623,-9.791179,-9.566864,60.273029,-7.512413
Netherlands,1.582312,0.383459,77.856630,-4.830444,67.849193,-3.868473,9.138654e+11,-3.798636,21.742168,-5.438727,67.447991,-5.533187,17.773889,-2.492099,-2.550170,69.849580,-4.276203
Poland,2.502175,13.831367,56.184326,0.132853,75.958371,-1.063587,5.966244e+11,-2.540659,17.248446,-12.139736,49.391143,-1.152519,27.682391,-5.165176,-7.214310,57.840480,-1.807116
Portugal,2.105403,-5.944107,37.032219,-18.636436,83.359854,-5.546050,2.285392e+11,-8.442456,18.752380,-5.748938,39.144454,-12.128736,19.359304,-5.412144,-8.002238,65.651943,-7.824849
Romania,3.967406,-14.944091,37.150090,-9.404692,79.895764,-3.569167,2.495113e+11,-3.747908,24.442159,2.588222,41.488013,-5.193327,26.890422,-1.917509,-4.395775,59.782633,-2.860591
Russian Federation,4.002045,0.201072,25.531215,-4.133744,70.891476,-4.894241,1.488322e+12,-2.683296,23.484070,-3.767320,20.430731,-12.074921,29.827064,-2.326257,0.499805,56.132943,-2.379066
Saudi Arabia,2.541905,-1.658356,26.182905,-10.239587,72.084444,-2.478745,7.033678e+11,-4.137670,27.626335,-13.835791,25.893684,-19.752896,40.105174,-5.966626,-8.966624,53.903272,-1.942633
Slovak Republic,1.757702,4.291577,85.436775,-7.278691,79.721622,-0.726056,1.051726e+11,-4.358754,19.352002,-19.849768,84.510399,-8.242653,27.364071,-13.118021,-16.042179,60.389012,0.095331
Slovenia,2.122207,3.884912,77.883011,-8.662698,70.777221,-3.754456,5.358961e+10,-4.229261,19.997666,-7.343662,68.657900,-9.578711,29.362777,-3.112577,-2.761639,56.925280,-3.780435
South Africa,2.527584,13.428591,27.778011,-11.950429,82.903777,-4.708073,3.354421e+11,-6.431975,12.745555,-24.730526,23.348835,-17.422974,23.422275,-12.591042,-12.326564,64.573671,-4.335044
Spain,3.148007,4.284523,30.620938,-20.147016,77.835693,-8.215184,1.281485e+12,-10.822886,20.691155,-11.433414,29.147786,-15.194837,20.370374,-10.443943,-12.075783,67.762231,-11.495840
Sweden,1.390201,1.794394,44.579653,-4.590643,70.593756,-3.436707,5.414872e+11,-2.944182,24.770876,-2.979845,39.944286,-5.567204,21.116668,-3.602199,-6.376728,66.141235,-3.233107
Turkiye,6.680560,5.857115,28.664856,-14.795788,71.924659,3.023917,7.199548e+11,1.793551,31.886233,NaN,32.475748,7.585720,28.018768,0.957043,3.242469,54.200204,0.642592
United Kingdom,0.583199,-9.940595,28.362276,-12.961316,83.124851,-9.508548,2.756900e+12,-9.270411,16.720014,-12.701793,28.066701,-15.768719,17.107108,-10.824565,-9.080059,72.722043,-8.938624
United States,1.059743,28.034568,10.162899,-13.562815,81.964990,-2.788095,2.089374e+13,-3.404590,21.151676,-3.956448,13.279559,-8.931712,18.438755,0.757656,-0.038291,80.136410,-0.578015

From here, we can start visualizing and modeling the data.

In [13]:
dataset_pivot.isna().sum()

Indicator Name
Agriculture, forestry, and fishing, value added (% of GDP)           1
Agriculture, forestry, and fishing, value added (annual % growth)    0
Exports of goods and services (% of GDP)                             0
Exports of goods and services (annual % growth)                      1
Final consumption expenditure (% of GDP)                             0
Final consumption expenditure (annual % growth)                      0
GDP (current US$)                                                    0
GDP growth (annual %)                                                0
Gross capital formation (% of GDP)                                   0
Gross capital formation (annual % growth)                            2
Imports of goods and services (% of GDP)                             0
Imports of goods and services (annual % growth)                      1
Industry (including construction), value added (% of GDP)            1
Industry (including construction), value added (annual % growth)     0
Manufacturing, value added (annual % growth)                         2
Services, value added (% of GDP)                                     1
Services, value added (annual % growth)                              0
dtype: int64

In [14]:
dataset_pivot.to_csv('Country_Indicators.csv')

Loading the csv back into notebook to fix the headers

In [15]:
dataset_processed = pd.read_csv('Country_Indicators.csv')

In [16]:
dataset_processed

,Country Name,"Agriculture, forestry, and fishing, value added (% of GDP)","Agriculture, forestry, and fishing, value added (annual % growth)",Exports of goods and services (% of GDP),Exports of goods and services (annual % growth),Final consumption expenditure (% of GDP),Final consumption expenditure (annual % growth),GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Gross capital formation (annual % growth),Imports of goods and services (% of GDP),Imports of goods and services (annual % growth),"Industry (including construction), value added (% of GDP)","Industry (including construction), value added (annual % growth)","Manufacturing, value added (annual % growth)","Services, value added (% of GDP)","Services, value added (annual % growth)"
0,Argentina,5.932404,-7.135723,16.591817,-17.326848,79.051086,-12.051155,3.895910e+11,-9.895269,14.019730,-11.016885,13.556325,-17.865058,23.311218,-9.369053,-7.760650,54.612674,-10.592109
1,Australia,2.006092,-10.068572,23.983854,-1.741033,73.802872,-0.416539,1.327836e+12,-0.003837,22.268947,NaN,20.055673,-7.666706,25.462096,0.049462,-1.370961,66.280808,0.643603
2,Austria,1.099909,-3.060587,51.435008,-10.759174,71.324373,-6.273300,4.332585e+11,-6.734514,25.901203,-4.646383,48.563935,-9.376541,25.457853,-5.659447,-6.997076,63.145665,-7.303380
3,Belgium,0.638362,-6.824667,80.042038,-5.459022,74.395963,-5.796638,5.216769e+11,-5.680734,24.197411,-6.928552,78.635413,-5.944309,19.479300,-3.093288,-3.687455,69.588938,-5.888087
4,Brazil,5.893246,3.753746,16.795068,-1.842905,83.369693,-5.223752,1.448566e+12,-3.878676,15.930622,-4.026255,16.095384,-9.840618,17.701653,-3.400928,-4.357614,62.795211,-4.344701
5,Bulgaria,3.505993,-3.301805,55.323289,-12.066986,78.191183,1.533585,6.988935e+10,-4.387150,20.339766,-5.279527,53.854238,-5.393745,21.923347,-8.218678,NaN,61.253206,-3.338591
6,Canada,NaN,3.328808,29.363448,-8.692684,79.806948,-4.559653,1.645423e+12,-5.233024,22.257070,-9.818021,31.419082,-10.858232,NaN,-6.310691,-9.685379,NaN,-4.967000
7,China,7.698643,3.132128,18.541060,NaN,55.330442,-0.273954,1.468767e+13,2.239702,43.366674,4.310804,16.048190,NaN,37.842787,2.464846,NaN,54.458561,1.947954
8,Croatia,3.216507,3.626613,42.024894,-22.725535,82.849174,-2.819567,5.720378e+10,-8.099761,23.908878,-2.813907,48.782821,-12.260688,21.155324,-1.523108,-3.863769,59.349699,-8.371669
9,Cyprus,1.930842,-1.384491,75.780512,-5.106329,83.355085,-0.942781,2.469210e+10,-4.984293,19.169241,-11.300714,78.304838,-2.547918,12.606087,-6.383702,-5.435013,74.286844,-4.432524
10,Denmark,1.306329,6.057835,54.881541,-7.006720,70.623184,-1.450882,3.560849e+11,-2.062125,22.925985,4.513192,48.430708,-4.079737,21.167106,-0.726394,-0.268787,64.550165,-3.027664
11,Estonia,2.166497,-6.062475,71.175819,-4.977873,71.046638,-0.966600,3.065029e+10,-2.951069,30.243912,14.772244,70.693544,0.856448,22.652102,-4.035191,-8.601872,62.692049,-2.064109
12,Finland,2.449211,4.506066,35.758734,-7.472933,75.341919,-2.708464,2.718370e+11,-2.299256,24.511859,-0.068067,35.520494,-6.643384,24.033278,-1.121114,-2.058841,60.113448,-3.108664
13,France,1.596840,-0.145683,27.873644,-15.817148,78.208271,-5.902311,2.630318e+12,-7.855256,23.811869,-9.028705,29.893784,-11.865744,16.445029,-11.229973,-10.932564,71.163379,-7.394614
14,Germany,0.735310,1.687117,43.416895,-9.319061,73.125735,-3.218028,3.846414e+12,-4.569617,21.149022,-6.366620,37.691652,-8.587234,26.531732,-7.352086,-10.023354,63.312547,-3.831393
15,Greece,4.230805,-4.214551,31.984002,-21.545369,92.616847,-5.495638,1.888352e+11,-9.019129,14.998070,10.560449,39.598919,-7.630608,14.997499,1.998168,7.468888,68.557587,-11.554613
16,Hungary,3.380822,-8.652733,79.008742,-6.076234,70.604617,-1.080930,1.567431e+11,-4.463221,27.315589,-6.638799,76.928948,-3.956720,24.627557,-7.201349,-6.996332,56.619027,-3.297772
17,India,18.228928,3.315789,18.708899,-9.238185,72.855488,-4.542697,2.667688e+12,-6.596081,27.896307,-11.387479,19.096455,-13.810104,24.531066,-3.264418,-0.599385,48.436857,-7.820996
18,Indonesia,13.702466,1.767005,17.271421,-8.139568,68.501977,-2.098435,1.058689e+12,-2.065005,32.354591,-6.897226,15.704174,-16.717418,38.251605,-2.800136,-2.931807,44.395919,-1.451549
19,Ireland,0.929474,-1.901458,131.112560,9.497584,37.700220,-5.195717,4.258890e+11,5.866976,40.881999,-22.052679,108.838469,-7.443220,37.953622,20.212608,23.046880,54.786282,-3.502460
20,Italy,2.009909,-4.738327,29.532511,-13.425831,78.634104,-7.938963,1.892574e+12,-9.025669,17.703516,-10.857464,25.870131,-12.110677,21.606753,-10.272397,-11.444301,66.815761,-8.493965
21,Japan,1.044271,-6.175335,15.558554,-11.801649,74.826695,-3.234071,5.040108e+12,-4.506905,25.414908,-5.074660,15.800157,-7.164526,29.016842,-4.331568,-6.626689,69.465400,-4.610832
22,Latvia,4.037779,0.796744,60.438155,-2.153328,77.129972,-4.898283,3.364546e+10,-3.769078,21.695383,-0.770587,59.263510,-2.464941,19.375057,-0.742569,-0.862682,63.492229,-4.904215
23,Lithuania,3.237023,9.438391,73.501436,0.434040,77.244129,-1.733888,5.654696e+10,-0.132431,13.470174,-13.014688,64.215741,-4.380182,24.978363,1.246179,1.125519,61.605659,-1.177114
24,Malta,0.437713,-14.817589,149.234806,-5.620201,65.375712,-3.248289,1.491704e+10,-8.348798,21.986185,-7.633401,136.596703,-2.228132,13.399901,-0.779476,-2.193171,76.870718,-8.331920
25,Mexico,3.798496,0.306680,39.603047,-7.292268,75.671800,-8.936602,1.087118e+12,-8.167358,19.161655,-19.419330,37.555725,-13.734970,29.620623,-9.791179,-9.566864,60.273029,-7.512413
26,Netherlands,1.582312,0.383459,77.856630,-4.830444,67.849193,-3.868473,9.138654e+11,-3.798636,21.742168,-5.438727,67.447991,-5.533187,17.773889,-2.492099,-2.550170,69.849580,-4.276203
27,Poland,2.502175,13.831367,56.184326,0.132853,75.958371,-1.063587,5.966244e+11,-2.540659,17.248446,-12.139736,49.391143,-1.152519,27.682391,-5.165176,-7.214310,57.840480,-1.807116
28,Portugal,2.105403,-5.944107,37.032219,-18.636436,83.359854,-5.546050,2.285392e+11,-8.442456,18.752380,-5.748938,39.144454,-12.128736,19.359304,-5.412144,-8.002238,65.651943,-7.824849
29,Romania,3.967406,-14.944091,37.150090,-9.404692,79.895764,-3.569167,2.495113e+11,-3.747908,24.442159,2.588222,41.488013,-5.193327,26.890422,-1.917509,-4.395775,59.782633,-2.860591
30,Russian Federation,4.002045,0.201072,25.531215,-4.133744,70.891476,-4.894241,1.488322e+12,-2.683296,23.484070,-3.767320,20.430731,-12.074921,29.827064,-2.326257,0.499805,56.132943,-2.379066
31,Saudi Arabia,2.541905,-1.658356,26.182905,-10.239587,72.084444,-2.478745,7.033678e+11,-4.137670,27.626335,-13.835791,25.893684,-19.752896,40.105174,-5.966626,-8.966624,53.903272,-1.942633
32,Slovak Republic,1.757702,4.291577,85.436775,-7.278691,79.721622,-0.726056,1.051726e+11,-4.358754,19.352002,-19.849768,84.510399,-8.242653,27.364071,-13.118021,-16.042179,60.389012,0.095331
33,Slovenia,2.122207,3.884912,77.883011,-8.662698,70.777221,-3.754456,5.358961e+10,-4.229261,19.997666,-7.343662,68.657900,-9.578711,29.362777,-3.112577,-2.761639,56.925280,-3.780435
34,South Africa,2.527584,13.428591,27.778011,-11.950429,82.903777,-4.708073,3.354421e+11,-6.431975,12.745555,-24.730526,23.348835,-17.422974,23.422275,-12.591042,-12.326564,64.573671,-4.335044
35,Spain,3.148007,4.284523,30.620938,-20.147016,77.835693,-8.215184,1.281485e+12,-10.822886,20.691155,-11.433414,29.147786,-15.194837,20.370374,-10.443943,-12.075783,67.762231,-11.495840
36,Sweden,1.390201,1.794394,44.579653,-4.590643,70.593756,-3.436707,5.414872e+11,-2.944182,24.770876,-2.979845,39.944286,-5.567204,21.116668,-3.602199,-6.376728,66.141235,-3.233107
37,Turkiye,6.680560,5.857115,28.664856,-14.795788,71.924659,3.023917,7.199548e+11,1.793551,31.886233,NaN,32.475748,7.585720,28.018768,0.957043,3.242469,54.200204,0.642592
38,United Kingdom,0.583199,-9.940595,28.362276,-12.961316,83.124851,-9.508548,2.756900e+12,-9.270411,16.720014,-12.701793,28.066701,-15.768719,17.107108,-10.824565,-9.080059,72.722043,-8.938624
39,United States,1.059743,28.034568,10.162899,-13.562815,81.964990,-2.788095,2.089374e+13,-3.404590,21.151676,-3.956448,13.279559,-8.931712,18.438755,0.757656,-0.038291,80.136410,-0.578015

Now to create a final column on the data to give it the classification number for our modeling phase.

The way we are defining a country's COVID respond will be based on the COVID-19 Stringency Index, created from the project "Oxford Coronavirus Government Response Tracker (OxCGRT)" that takes nine metrics to calculate a score from 0-100 on government strictness during the COVID-19 pandemic. These metrics include things such as: restrictions on public gatherings, school closures, workplace closures, and so on. The webpage I'm getting the data from is <a href="https://ourworldindata.org/metrics-explained-covid19-stringency-index">here</a> but the source will also be below.

Using the tool embedded into the webpage to provide the Stringency Index, I set the starting time as Jan 1st, 2020, and the ending time at Dec 31, 2020, to only include measures during 2020, as that is the time that our economic data is covering. 

From there, we wanted distinct categories for the classification modeling section of our project, so I converted the 0-100 scale into three different groups.

A score of 0-50 will give a 1, meaning that the country's government responded the least out of the three groups.

A score of 51-75 will give a 2, meaning that there were more government policies than the first group, but less than the third group.

And finally, a score of 76-100 will give a 3, meaning that these countries had the most policies compared to the other two groups.

For reference, the score is calculated by government policies, not how well they worked or how hard a country was hit with infection. This could lead to some interesting surprises in countries that could possibly be explained for other reasons. One that surprised me was Japan with a low score of 45.37, but it could be explained by the fact that they shut their borders and were able to isolate from the world better due to their geography as an island nation. Another island nation in our group, Malta, had a close score of 52.78, which might lead to a potential pattern, but looking at other islands like Cyprus and Australia, which had scores in the 70s, shows that not every island behaved the same. (Even looking at New Zealand, which didn't make the cut in our dataset, the country had a score of 22.22!)

I decided to group the classification groups that way due to the fact that there aren't many countries in our selected group that faltered less than 50, and most were in the 50-80 area. I didn't want them all to be in the same group, as that would defeat the purpose of our classification.

Now, to implement this data and add it to our dataframe. For reference, I'm just reading the numbers off of the webpage and manually adding them as the data download they provide uses the raw metrics that the tool on the webpage uses to caluclate the index.

In [17]:
index_classification = np.array([3, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 3, 3, 1, 2, 
                        3, 2, 2, 3, 3, 3, 3, 1, 2, 2, 3, 1, 3, 2, 3, 3, 2])

In [18]:
len(index_classification)

40

In [19]:
dataset_processed['Response Group'] = index_classification.tolist()

In [20]:
dataset_processed

,Country Name,"Agriculture, forestry, and fishing, value added (% of GDP)","Agriculture, forestry, and fishing, value added (annual % growth)",Exports of goods and services (% of GDP),Exports of goods and services (annual % growth),Final consumption expenditure (% of GDP),Final consumption expenditure (annual % growth),GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Gross capital formation (annual % growth),Imports of goods and services (% of GDP),Imports of goods and services (annual % growth),"Industry (including construction), value added (% of GDP)","Industry (including construction), value added (annual % growth)","Manufacturing, value added (annual % growth)","Services, value added (% of GDP)","Services, value added (annual % growth)",Response Group
0,Argentina,5.932404,-7.135723,16.591817,-17.326848,79.051086,-12.051155,3.895910e+11,-9.895269,14.019730,-11.016885,13.556325,-17.865058,23.311218,-9.369053,-7.760650,54.612674,-10.592109,3
1,Australia,2.006092,-10.068572,23.983854,-1.741033,73.802872,-0.416539,1.327836e+12,-0.003837,22.268947,NaN,20.055673,-7.666706,25.462096,0.049462,-1.370961,66.280808,0.643603,2
2,Austria,1.099909,-3.060587,51.435008,-10.759174,71.324373,-6.273300,4.332585e+11,-6.734514,25.901203,-4.646383,48.563935,-9.376541,25.457853,-5.659447,-6.997076,63.145665,-7.303380,3
3,Belgium,0.638362,-6.824667,80.042038,-5.459022,74.395963,-5.796638,5.216769e+11,-5.680734,24.197411,-6.928552,78.635413,-5.944309,19.479300,-3.093288,-3.687455,69.588938,-5.888087,2
4,Brazil,5.893246,3.753746,16.795068,-1.842905,83.369693,-5.223752,1.448566e+12,-3.878676,15.930622,-4.026255,16.095384,-9.840618,17.701653,-3.400928,-4.357614,62.795211,-4.344701,2
5,Bulgaria,3.505993,-3.301805,55.323289,-12.066986,78.191183,1.533585,6.988935e+10,-4.387150,20.339766,-5.279527,53.854238,-5.393745,21.923347,-8.218678,NaN,61.253206,-3.338591,2
6,Canada,NaN,3.328808,29.363448,-8.692684,79.806948,-4.559653,1.645423e+12,-5.233024,22.257070,-9.818021,31.419082,-10.858232,NaN,-6.310691,-9.685379,NaN,-4.967000,2
7,China,7.698643,3.132128,18.541060,NaN,55.330442,-0.273954,1.468767e+13,2.239702,43.366674,4.310804,16.048190,NaN,37.842787,2.464846,NaN,54.458561,1.947954,3
8,Croatia,3.216507,3.626613,42.024894,-22.725535,82.849174,-2.819567,5.720378e+10,-8.099761,23.908878,-2.813907,48.782821,-12.260688,21.155324,-1.523108,-3.863769,59.349699,-8.371669,2
9,Cyprus,1.930842,-1.384491,75.780512,-5.106329,83.355085,-0.942781,2.469210e+10,-4.984293,19.169241,-11.300714,78.304838,-2.547918,12.606087,-6.383702,-5.435013,74.286844,-4.432524,2
10,Denmark,1.306329,6.057835,54.881541,-7.006720,70.623184,-1.450882,3.560849e+11,-2.062125,22.925985,4.513192,48.430708,-4.079737,21.167106,-0.726394,-0.268787,64.550165,-3.027664,2
11,Estonia,2.166497,-6.062475,71.175819,-4.977873,71.046638,-0.966600,3.065029e+10,-2.951069,30.243912,14.772244,70.693544,0.856448,22.652102,-4.035191,-8.601872,62.692049,-2.064109,2
12,Finland,2.449211,4.506066,35.758734,-7.472933,75.341919,-2.708464,2.718370e+11,-2.299256,24.511859,-0.068067,35.520494,-6.643384,24.033278,-1.121114,-2.058841,60.113448,-3.108664,2
13,France,1.596840,-0.145683,27.873644,-15.817148,78.208271,-5.902311,2.630318e+12,-7.855256,23.811869,-9.028705,29.893784,-11.865744,16.445029,-11.229973,-10.932564,71.163379,-7.394614,2
14,Germany,0.735310,1.687117,43.416895,-9.319061,73.125735,-3.218028,3.846414e+12,-4.569617,21.149022,-6.366620,37.691652,-8.587234,26.531732,-7.352086,-10.023354,63.312547,-3.831393,3
15,Greece,4.230805,-4.214551,31.984002,-21.545369,92.616847,-5.495638,1.888352e+11,-9.019129,14.998070,10.560449,39.598919,-7.630608,14.997499,1.998168,7.468888,68.557587,-11.554613,3
16,Hungary,3.380822,-8.652733,79.008742,-6.076234,70.604617,-1.080930,1.567431e+11,-4.463221,27.315589,-6.638799,76.928948,-3.956720,24.627557,-7.201349,-6.996332,56.619027,-3.297772,2
17,India,18.228928,3.315789,18.708899,-9.238185,72.855488,-4.542697,2.667688e+12,-6.596081,27.896307,-11.387479,19.096455,-13.810104,24.531066,-3.264418,-0.599385,48.436857,-7.820996,2
18,Indonesia,13.702466,1.767005,17.271421,-8.139568,68.501977,-2.098435,1.058689e+12,-2.065005,32.354591,-6.897226,15.704174,-16.717418,38.251605,-2.800136,-2.931807,44.395919,-1.451549,2
19,Ireland,0.929474,-1.901458,131.112560,9.497584,37.700220,-5.195717,4.258890e+11,5.866976,40.881999,-22.052679,108.838469,-7.443220,37.953622,20.212608,23.046880,54.786282,-3.502460,3
20,Italy,2.009909,-4.738327,29.532511,-13.425831,78.634104,-7.938963,1.892574e+12,-9.025669,17.703516,-10.857464,25.870131,-12.110677,21.606753,-10.272397,-11.444301,66.815761,-8.493965,3
21,Japan,1.044271,-6.175335,15.558554,-11.801649,74.826695,-3.234071,5.040108e+12,-4.506905,25.414908,-5.074660,15.800157,-7.164526,29.016842,-4.331568,-6.626689,69.465400,-4.610832,1
22,Latvia,4.037779,0.796744,60.438155,-2.153328,77.129972,-4.898283,3.364546e+10,-3.769078,21.695383,-0.770587,59.263510,-2.464941,19.375057,-0.742569,-0.862682,63.492229,-4.904215,2
23,Lithuania,3.237023,9.438391,73.501436,0.434040,77.244129,-1.733888,5.654696e+10,-0.132431,13.470174,-13.014688,64.215741,-4.380182,24.978363,1.246179,1.125519,61.605659,-1.177114,3
24,Malta,0.437713,-14.817589,149.234806,-5.620201,65.375712,-3.248289,1.491704e+10,-8.348798,21.986185,-7.633401,136.596703,-2.228132,13.399901,-0.779476,-2.193171,76.870718,-8.331920,2
25,Mexico,3.798496,0.306680,39.603047,-7.292268,75.671800,-8.936602,1.087118e+12,-8.167358,19.161655,-19.419330,37.555725,-13.734970,29.620623,-9.791179,-9.566864,60.273029,-7.512413,2
26,Netherlands,1.582312,0.383459,77.856630,-4.830444,67.849193,-3.868473,9.138654e+11,-3.798636,21.742168,-5.438727,67.447991,-5.533187,17.773889,-2.492099,-2.550170,69.849580,-4.276203,3
27,Poland,2.502175,13.831367,56.184326,0.132853,75.958371,-1.063587,5.966244e+11,-2.540659,17.248446,-12.139736,49.391143,-1.152519,27.682391,-5.165176,-7.214310,57.840480,-1.807116,3
28,Portugal,2.105403,-5.944107,37.032219,-18.636436,83.359854,-5.546050,2.285392e+11,-8.442456,18.752380,-5.748938,39.144454,-12.128736,19.359304,-5.412144,-8.002238,65.651943,-7.824849,3
29,Romania,3.967406,-14.944091,37.150090,-9.404692,79.895764,-3.569167,2.495113e+11,-3.747908,24.442159,2.588222,41.488013,-5.193327,26.890422,-1.917509,-4.395775,59.782633,-2.860591,3
30,Russian Federation,4.002045,0.201072,25.531215,-4.133744,70.891476,-4.894241,1.488322e+12,-2.683296,23.484070,-3.767320,20.430731,-12.074921,29.827064,-2.326257,0.499805,56.132943,-2.379066,1
31,Saudi Arabia,2.541905,-1.658356,26.182905,-10.239587,72.084444,-2.478745,7.033678e+11,-4.137670,27.626335,-13.835791,25.893684,-19.752896,40.105174,-5.966626,-8.966624,53.903272,-1.942633,2
32,Slovak Republic,1.757702,4.291577,85.436775,-7.278691,79.721622,-0.726056,1.051726e+11,-4.358754,19.352002,-19.849768,84.510399,-8.242653,27.364071,-13.118021,-16.042179,60.389012,0.095331,2
33,Slovenia,2.122207,3.884912,77.883011,-8.662698,70.777221,-3.754456,5.358961e+10,-4.229261,19.997666,-7.343662,68.657900,-9.578711,29.362777,-3.112577,-2.761639,56.925280,-3.780435,3
34,South Africa,2.527584,13.428591,27.778011,-11.950429,82.903777,-4.708073,3.354421e+11,-6.431975,12.745555,-24.730526,23.348835,-17.422974,23.422275,-12.591042,-12.326564,64.573671,-4.335044,1
35,Spain,3.148007,4.284523,30.620938,-20.147016,77.835693,-8.215184,1.281485e+12,-10.822886,20.691155,-11.433414,29.147786,-15.194837,20.370374,-10.443943,-12.075783,67.762231,-11.495840,3
36,Sweden,1.390201,1.794394,44.579653,-4.590643,70.593756,-3.436707,5.414872e+11,-2.944182,24.770876,-2.979845,39.944286,-5.567204,21.116668,-3.602199,-6.376728,66.141235,-3.233107,2
37,Turkiye,6.680560,5.857115,28.664856,-14.795788,71.924659,3.023917,7.199548e+11,1.793551,31.886233,NaN,32.475748,7.585720,28.018768,0.957043,3.242469,54.200204,0.642592,3
38,United Kingdom,0.583199,-9.940595,28.362276,-12.961316,83.124851,-9.508548,2.756900e+12,-9.270411,16.720014,-12.701793,28.066701,-15.768719,17.107108,-10.824565,-9.080059,72.722043,-8.938624,3
39,United States,1.059743,28.034568,10.162899,-13.562815,81.964990,-2.788095,2.089374e+13,-3.404590,21.151676,-3.956448,13.279559,-8.931712,18.438755,0.757656,-0.038291,80.136410,-0.578015,2

Now to save this csv again, and send it to the modeling and visualization phases.

In [21]:
dataset_processed.to_csv('Country_Indicators_Response_Groups.csv')

## Sources

<ul>
    <li>https://datacatalog.worldbank.org/search/dataset/0037712/World-Development-Indicators</li>
    <li>https://ourworldindata.org/metrics-explained-covid19-stringency-index</li>
</ul>